# Generated by Django 3.0.2 on 2020-04-18 16:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_title', models.CharField(default=' ', max_length=255)),
                ('number_of_bids', models.IntegerField()),
                ('minimum_price', models.DecimalField(decimal_places=2, default=0.01, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('product_status', models.CharField(choices=[('In Stock', 'In Stock'), ('Sold', 'Sold')], default='In Stock', max_length=30)),
                ('time_starting', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('time_ending', models.DateTimeField(default=datetime.datetime(2020, 4, 19, 16, 29, 47, 552173, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('Books', 'Books'), ('Clothes', 'Clothes'), ('Groceries', 'Groceries'), ('Health & Beauty', 'Health & Beauty'), ('Home & Furniture', 'Home & Furniture'), ('Jewellery', 'Jewellery'), ('Technology', 'Technology'), ('Toys', 'Toys'), ('Other', 'Other')], default='Other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('item_condition', models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Used', 'Used'), ('Old with Defects', 'Old with Defects')], default='New', max_length=30)),
                ('item_owner_info', models.CharField(default='', max_length=255)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_title', models.CharField(default=' ', max_length=255)),
                ('bid', models.DecimalField(decimal_places=2, default=0.01, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Auction')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Product'),
        ),
    ]
