# Generated by Django 3.0.2 on 2020-04-18 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 16, 34, 3, 509627, tzinfo=utc)),
        ),
    ]
