# Generated by Django 3.0.2 on 2020-04-18 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20200418_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_ending',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 16, 43, 54, 548091, tzinfo=utc)),
        ),
    ]
